version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: MusicRecommender_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alex1111
      POSTGRES_DB: MusicRecommender
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MusicRecommender"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MusicRecommender_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MusicRecommender;Username=postgres;Password=Alex1111

volumes:
  pgdata:
