using System.ComponentModel.DataAnnotations;

namespace MusicRecommender.Models;

/// <summary>
/// Represents one imported playlist source. A playlist is the parent entity for extracted track
/// metadata and is also used to group recommendation history.
/// </summary>
public class Playlist
{
    /// <summary>
    /// Internal database identifier used by API routes and foreign keys.
    /// </summary>
    [Key]
    public int Id { get; set; } // Primary key generated by the database.

    /// <summary>
    /// Original Spotify or YouTube playlist URL submitted by the user. This stays required because
    /// it identifies the external source and lets the UI display where the import came from.
    /// </summary>
    [Required]
    public string ExternalUrl { get; set; } = string.Empty; // Source URL submitted by the user.

    /// <summary>
    /// Optional user-defined display name. When null, the frontend falls back to the external URL.
    /// </summary>
    public string? Name { get; set; } // Friendly title chosen by the user.

    /// <summary>
    /// UTC timestamp for when the playlist was imported and persisted.
    /// </summary>
    public DateTime ProcessedAt { get; set; } = DateTime.UtcNow; // Import time used for sorting.

    /// <summary>
    /// Tracks extracted from the playlist during import. The collection is initialized so new
    /// playlists can receive TrackMetadata children before being saved.
    /// </summary>
    public ICollection<TrackMetadata> Tracks { get; set; } = new List<TrackMetadata>(); // Child track rows.
}
